### ISSUE TITLE
Issue using module inside VCSode

### ISSUE THREAD

**Issue by jacob-shand** [benjaminwestern/tclogger#1]
### Problem
Module does not get loaded when using debug in VSCode for Python

### Workaround
Using it via the command line works fine

### Replicate issue
- Create new Python file in VSCode
- Type "import tclogger"
- Attempt to debug/run the file
<img width="909" alt="image" src="https://user-images.githubusercontent.com/69992586/209291264-4a7c3f84-c38d-4824-a5d2-8b315785168b.png">

**Comment by benjaminwestern** [comment]
Thanks Jacob,

Could you please provide me with the VSCode version, python version and vscode python settings so I can attempt to replicate this problem.

Cheers! BW

**Comment by jacob-shand** [comment]
Python version: 3.10.8
VSCode version: 1.74.2
No settings set as override for Python is VSCode

**Comment by benjaminwestern** [comment]
After reviewing your original notes, it appears your VSCode is using 3.10.6. Are you utilising virtualenv at all? For comparison, I utilise brew to install python and my launch command looks like this:

```cd /Users/benjaminwestern/code/reference ; /usr/bin/env /opt/homebrew/bin/python3 /Users/benjaminwestern/.
vscode/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 57851 ```

It appears we are utilising the same python extension in VSCode, so the only visible difference I can ascertain at the moment  is that your VSCode is potentially using a different version of python that the path installed version on your machine.

Things you can try:
Check you aren't using a python virtual envirionment
1. Command + Shift + P
2. Type Python: Create Environment
3. Are there any other environments listed - as mine only displays default:
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/72841840/209408817-39672ece-b95a-4267-b9a7-8c4fbea01651.png">

Check your python debugger launch config:
1. Click Run & Debug from the bar menu
2. Click the cog next to python file listed at the top of the debug window:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/72841840/209409040-7de8de9a-363c-466e-b0e7-70983737a393.png">
3. My launch config is as below:
```
{
    "configurations": [
        {
            "name": "Python: File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "justMyCode": true
        }
    ]
}
```

Let me know what you find - Happy to help :) I made the assumption you were using Linux or MacOS due to your VSCode Run Path

Cheers BW

**Comment by benjaminwestern** [comment]
@jacob-shand I also note that you are using pyenv.

You can see what version your pyenv is set as using the following:
`pyenv versions`

I suspect the starred version will be different to your `python --version` output.

If you wish to install tclogger in the 3.10.6 version you need to ensure pyenv local or global is configured in your terminal so that when pip installs the package it is installed for your python version - Here is an example:

```
pyenv local 3.10.6
pip install tclogger
```
Commands can be found here: [Pyenv Commands](https://github.com/pyenv/pyenv/blob/master/COMMANDS.md)

**Comment by jacob-shand** [comment]
Not entirely sure what is happening, but I think this is a VSCode behavioural error. Running "pip install" in the terminal gives me "requirement already satisfied", but upon executing the code it appears to execute inside an environment that doesn't have TClogger installed.

I've created a VENV and activated it, and then installed your package and my code works fine.

Chalk this up to VSCode/VirtualEnv configuration issue, although the terminal is showing me that it's already installed.

Thanks for your help! Ill close this one off now :)
<img width="524" alt="image" src="https://user-images.githubusercontent.com/69992586/209416793-60678a0f-105b-4ea2-bcbc-a87b64ec7293.png">
<img width="379" alt="image" src="https://user-images.githubusercontent.com/69992586/209416797-659b20f6-c2a8-40bd-be30-bab0c2a57769.png">
